version: '3.1'

services:

  eebasket-db:
    image: mysql:5.7
    container_name: eebasket-db
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - nginx

  eebasket-wordpress:
    image: wordpress
    container_name: eebasket-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: eebasket-db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - eebasket-db
    networks:
      - nginx

  eebasket-nginx:
    image: eebasket-nginx
    container_name: eebasket-nginx
    hostname: eebasket-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - eebasket-db
      - eebasket-wordpress
    ports:
      - "8089:80"
    networks:
      - nginx

volumes:
  wordpress:
  db:

networks:
  nginx:
    external: true
